# Site settings
title: Steamworks.NET
email: contact@rileylabrecque.com
description: "Steamworks.NET Documentation"
baseurl: ""
url: "/"
twitter_username: rileylabrecque
github_username:  rlabrecque

# Build settings
markdown: kramdown
permalink: pretty
titlecase: false

navigation:
- text: Installation
  url: /installation/
- text: Getting started
  url: /gettingstarted/
- text: SteamManager
  url: /steammanager/
- text: Frequently Asked Questions
  url: /faq/
- text: Support
  url: /support/
- text: Games using Steamworks.NET
  url: /gameslist/
- text: Changelog
  url: /changelog/

destination: ../Steamworks.NET_public
